/*
 * libFuzzer harness for ngx_http_brotli_accept_encoding() and the
 * helpers it calls (ngx_http_brotli_coding_weight / eval_qvalue /
 * skip_quoted).
 *
 * Why this target: it parses attacker-controlled Accept-Encoding header
 * bytes in C and does pointer arithmetic against ae->data / ae->len. The
 * parser is a fully length-bounded token walker (no NUL reliance), so
 * this harness deliberately feeds it a buffer sized to EXACTLY ae->len
 * with NO trailing NUL — ASAN then flags any single byte read at or past
 * ae->len. That is a hard regression gate against reintroducing a
 * NUL-bounded scan (the parser this one replaced was built on
 * ngx_strcasestrn, which is exactly such a scan).
 *
 * The real functions live in ../ngx_http_brotli_common.h and depend on
 * the nginx tree. fuzz/extract_parser.sh slices just those functions into
 * generated_parser.inc at build time, so we always fuzz the SHIPPED code
 * with no copy drift. ngx_shim.h provides the tiny nginx surface it needs
 * with faithful upstream semantics.
 *
 * Ported from nginx-zstd-module's fuzz harness, including the
 * independently written reference oracle (retargeted from "zstd" to
 * "br"): two implementations rarely share the same subtle bug, so a
 * divergence on an input the reference is confident about is a real
 * semantic defect, not a style nit.
 *
 * Build (see fuzz/build.sh):
 *   clang -g -O1 -fsanitize=fuzzer,address,undefined \
 *       fuzz_accept_encoding.c -o fuzz_accept_encoding
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "ngx_shim.h"

/* Generated by fuzz/extract_parser.sh from ../ngx_http_brotli_common.h. */
#include "generated_parser.inc"


/*
 * Independent reference oracle. Deliberately conservative: returns -1
 * ("unsure") for any input outside a small, unambiguous grammar. For the
 * inputs it IS confident about it returns 1 (accept) / 0 (decline), and
 * the harness asserts the production parser agrees.
 */
static int
ref_accepts(const uint8_t *d, size_t n)
{
    size_t  i = 0;
    int     br_q = -1;       /* explicit br weight in milli, -1 absent */
    int     star_q = -1;     /* "*" weight, -1 absent */

    while (i < n) {
        size_t  ts, te;
        int     is_br, is_star, q;

        /* OWS / empty elements */
        while (i < n && (d[i] == ' ' || d[i] == '\t' || d[i] == ',')) i++;
        if (i >= n) break;

        /*
         * A quoted-string can never be a valid coding name. The
         * production parser declines such an element; mirror that
         * confidently so the differential GATES the name-position
         * phantom-token class (`"a,br "` must NOT yield br). Bail to
         * "unsure" only on a '\' escape or an unterminated quote.
         */
        if (d[i] == '"') {
            while (i < n && d[i] != ',') {
                if (d[i] == '"') {
                    i++;                            /* opening DQUOTE */
                    while (i < n && d[i] != '"') {
                        if (d[i] == '\\') return -1;  /* escapes → unsure */
                        i++;
                    }
                    if (i >= n) return -1;          /* unterminated quote */
                    i++;                            /* closing DQUOTE */
                } else {
                    i++;
                }
            }
            if (i < n) i++;                         /* consume the ',' */
            continue;                               /* non-matching element */
        }

        /* token name: letters/digits or a lone '*' */
        ts = i;
        while (i < n && ((d[i] >= 'A' && d[i] <= 'Z')
                         || (d[i] >= 'a' && d[i] <= 'z')
                         || (d[i] >= '0' && d[i] <= '9')
                         || d[i] == '*' || d[i] == '-' || d[i] == '_')) {
            i++;
        }
        te = i;
        if (te == ts) {
            return -1;          /* unexpected leading byte: give up */
        }

        is_star = (te - ts == 1 && d[ts] == '*');
        is_br = (te - ts == 2
                 && (d[ts] | 0x20) == 'b' && (d[ts + 1] | 0x20) == 'r');

        while (i < n && (d[i] == ' ' || d[i] == '\t')) i++;

        /*
         * Junk after the name and OWS ("br x"): the element matches
         * nothing. Mirror the production rule confidently — skip to the
         * next top-level comma; bail to "unsure" on a DQUOTE so
         * quote-skipping subtleties stay out of the confident path.
         */
        if (i < n && d[i] != ';' && d[i] != ',') {
            is_br = 0;
            is_star = 0;
            while (i < n && d[i] != ',') {
                if (d[i] == '"') return -1;
                i++;
            }
        }

        q = 1000;   /* no weight → q=1 */

        /*
         * Parameters: understand a single "q" weight; for a non-"q" param
         * confidently skip a token value or a simple quoted-string value.
         * Anything outside this shape returns -1 (unsure).
         */
        {
            int  q_seen = 0;

            while (i < n && d[i] == ';') {
                size_t  ps, pe;
                int     is_qp;

                i++;    /* ';' */
                while (i < n && (d[i] == ' ' || d[i] == '\t')) i++;

                ps = i;
                while (i < n && d[i] != '=' && d[i] != ';' && d[i] != ','
                       && d[i] != ' ' && d[i] != '\t' && d[i] != '"') {
                    i++;
                }
                pe = i;

                /*
                 * Empty parameter name ("br;;q=1", trailing "br;"):
                 * RFC 9110 has no empty-parameter production, so the
                 * element is malformed and matches nothing (mirrors
                 * the production rule; siblings' parent #142). Skip to
                 * the next top-level comma; bail to "unsure" on a
                 * DQUOTE to keep quote-skipping out of this path.
                 */
                if (pe == ps) {
                    is_br = 0;
                    is_star = 0;
                    while (i < n && d[i] != ',') {
                        if (d[i] == '"') return -1;
                        i++;
                    }
                    break;
                }

                is_qp = (pe - ps == 1 && (d[ps] == 'q' || d[ps] == 'Q'));

                while (i < n && (d[i] == ' ' || d[i] == '\t')) i++;

                if (i >= n || d[i] != '=') {
                    if (is_qp) return -1;          /* bare "q" is malformed */
                    continue;                       /* valueless non-q param */
                }

                i++;    /* '=' */
                while (i < n && (d[i] == ' ' || d[i] == '\t')) i++;

                if (is_qp) {
                    if (q_seen) return -1;          /* repeated "q" */
                    q_seen = 1;

                    if (i >= n) return -1;          /* "q=" with no value */

                    if (d[i] == '0') {
                        int scale = 100;
                        i++;
                        q = 0;
                        if (i < n && d[i] == '.') {
                            i++;
                            while (i < n && d[i] >= '0' && d[i] <= '9'
                                   && scale > 0) {
                                q += (d[i] - '0') * scale;
                                scale /= 10;
                                i++;
                            }
                        }
                    } else if (d[i] == '1') {
                        int k = 0;
                        i++;
                        q = 1000;
                        if (i < n && d[i] == '.') {
                            i++;
                            while (i < n && d[i] == '0' && k < 3) { i++; k++; }
                        }
                    } else {
                        return -1;
                    }

                } else if (i < n && d[i] == '"') {
                    i++;                            /* opening DQUOTE */
                    while (i < n && d[i] != '"') {
                        if (d[i] == '\\') return -1; /* escapes → unsure */
                        i++;
                    }
                    if (i >= n) return -1;          /* unterminated quote */
                    i++;                            /* closing DQUOTE */

                } else {
                    /* bare token value */
                    while (i < n && d[i] != ';' && d[i] != ','
                           && d[i] != ' ' && d[i] != '\t' && d[i] != '"') {
                        i++;
                    }
                }

                /* after a value only OWS then ';' / ',' / end is valid */
                while (i < n && (d[i] == ' ' || d[i] == '\t')) i++;
                if (i < n && d[i] != ';' && d[i] != ',') return -1;
            }
        }

        if (is_br) {
            br_q = q;
        } else if (is_star) {
            star_q = q;
        }

        /* element consumed: only a ',' separator or end may remain */
        if (i < n) {
            if (d[i] != ',') return -1;            /* trailing junk */
            i++;
        }
    }

    if (br_q >= 0) return br_q > 0 ? 1 : 0;
    if (star_q >= 0) return star_q > 0 ? 1 : 0;
    return 0;
}


int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    /*
     * Do NOT append a trailing NUL: allocate exactly `size` bytes (one
     * byte when size == 0, since malloc(0) is implementation-defined).
     * ASAN then turns any read at or past ae->len — i.e. any
     * reintroduced NUL-bounded scan — into an immediate, reproducible
     * heap-buffer-overflow failure.
     */
    size_t  alloc = size ? size : 1;
    u_char *buf = (u_char *) malloc(alloc);
    if (buf == NULL) {
        return 0;
    }

    if (size) {
        memcpy(buf, data, size);
    }

    ngx_str_t ae;
    ae.data = buf;
    ae.len  = size;

    ngx_int_t rc = ngx_http_brotli_accept_encoding(&ae);

    /* Result must be one of the two documented sentinels. */
    if (rc != NGX_OK && rc != NGX_DECLINED) {
        __builtin_trap();
    }

    /*
     * Semantic differential: when the independent reference is
     * confident, the production parser must agree. -1 = reference unsure
     * (ambiguous edge) → no assertion.
     */
    {
        int ref = ref_accepts(data, size);
        if (ref >= 0 && (ref == 1) != (rc == NGX_OK)) {
            __builtin_trap();
        }
    }

    /*
     * The generic walker exercised with a second token ("dcb",
     * explicit-only — the future RFC 9842 lookup) so the parameterized
     * name-match path also runs under ASAN on every input. Weights are
     * milli-q by contract: anything outside -1..1000 means the walker
     * fell through a path it should not have.
     */
    {
        ngx_int_t dq = ngx_http_brotli_coding_weight(&ae, "dcb",
                                                     sizeof("dcb") - 1, 0);
        if (dq < -1 || dq > 1000) {
            __builtin_trap();
        }
    }

    free(buf);
    return 0;
}
