#!/bin/bash
# Unit fixture for the strict-mode dictionary path walk,
# ngx_http_zstd_dict_file_open_strict() and its per-directory check, in
# src/ngx_http_zstd_dict_file.h -- THE authoritative copy, included
# directly. The four system calls the walk makes are function-like macros
# over scripted fakes in test_dict_walk_unit.c, so every exit is reached
# deterministically, including the ones no shell fixture can stage. No
# nginx tree, no zstd needed -- pure C, POSIX only.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root.
cd "$(dirname "$0")/../.."

HDR="src/ngx_http_zstd_dict_file.h"
SRC="src/ngx_http_zstd_filter_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-dict-walk-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

for marker in 'ngx_http_zstd_dict_file_open_strict(ngx_str_t \*path, int flags,' \
    'ngx_http_zstd_dict_file_check_dir(int fd, ngx_http_zstd_dict_walk_t \*walk)' \
    'NGX_HTTP_ZSTD_DICT_WALK_DIR_WRITABLE' 'O_NOFOLLOW'; do
    if ! grep -q "$marker" "$HDR"; then
        echo "FAIL: $HDR lacks marker: $marker" >&2
        exit 1
    fi
done

# Production must route strict mode through the header's walk and must not
# open path components on its own: an openat() CALL anywhere in the module
# (an identifier as its first argument -- the diagnostics only ever spell
# it with a quote or an empty list) is the walk restored inside it.
if ! grep -q 'ngx_http_zstd_dict_file_open_strict(path, flags, &walk)' "$SRC"; then
    echo "FAIL: $SRC no longer routes strict mode through ngx_http_zstd_dict_file_open_strict()" >&2
    exit 1
fi
if grep -Eq 'openat\([A-Za-z_]' "$SRC"; then
    echo "FAIL: $SRC calls openat() on its own again; the walk belongs in $HDR" >&2
    exit 1
fi

# Every refusal the walk can report must have a message in the module's
# switch: a code added to the header without a case is a silent refusal.
# The extraction itself is checked first: renamed or reformatted enum
# markers would yield no codes, and a loop over nothing passes.
codes=$(sed -n '/^typedef enum {$/,/^} ngx_http_zstd_dict_walk_rc_t;$/p' "$HDR" \
        | grep -o 'NGX_HTTP_ZSTD_DICT_WALK_[A-Z_]*' | sort -u || true)
ncodes=$(printf '%s\n' "$codes" | grep -c . || true)
if [ "$ncodes" -lt 2 ]; then
    echo "FAIL: could not extract the walk refusal codes from $HDR (found $ncodes); the enum was renamed or reformatted" >&2
    exit 1
fi
for code in $codes; do
    if ! grep -q "case $code:" "$SRC"; then
        echo "FAIL: $SRC has no diagnostic for $code" >&2
        exit 1
    fi
done

# The logging shell itself is extracted verbatim (it is `static` in the
# module) and compiled into the fixture, which calls it with every code and
# counts the diagnostics -- so a case label that no longer logs, not just a
# missing label, fails the run. Locate pipelines end in `|| true` so a
# missing pattern reaches its diagnostic under pipefail.
SIG='ngx_http_zstd_log_dict_walk(ngx_conf_t \*cf, ngx_str_t \*path,$'
SIG_LINE="$(grep -n "^${SIG}" "$SRC" | head -1 | cut -d: -f1 || true)"
if [ -z "$SIG_LINE" ]; then
    echo "FAIL: could not locate ngx_http_zstd_log_dict_walk() in $SRC" >&2
    exit 1
fi
START_LINE=$((SIG_LINE - 1))
if ! sed -n "${START_LINE}p" "$SRC" | grep -q '^static void$'; then
    echo "FAIL: line $START_LINE of $SRC is not the log shell's 'static void' line" >&2
    exit 1
fi
REL_END="$(tail -n "+${START_LINE}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1 || true)"
if [ -z "$REL_END" ]; then
    echo "FAIL: could not find the closing brace of ngx_http_zstd_log_dict_walk() in $SRC" >&2
    exit 1
fi
END_LINE=$((START_LINE + REL_END - 1))
{
    echo "/* Generated by test_dict_walk_unit.sh: verbatim extraction of"
    echo " * ngx_http_zstd_log_dict_walk() from $SRC lines ${START_LINE}-${END_LINE}."
    echo " * Do not edit. */"
    sed -n "${START_LINE},${END_LINE}p" "$SRC"
} > "$OUT/generated_log_dict_walk.inc"
if ! grep -q 'switch (walk->rc)' "$OUT/generated_log_dict_walk.inc"; then
    echo "FAIL: the extracted log shell is not the switch over walk->rc" >&2
    exit 1
fi

"$CC" -std=gnu99 -Wall -Wextra -Werror -O1 -I ci/tools -I "$OUT" \
    -o "$OUT/test_dict_walk_unit" ci/tools/test_dict_walk_unit.c
"$OUT/test_dict_walk_unit"

echo "OK: dict walk unit fixture (against $HDR)"
