#!/bin/bash
# Copyright (C) 2026 Thijs Eilander
# SPDX-License-Identifier: BSD-2-Clause
#
# Unit fixture for ngx_http_zstd_ratio_parts() -- the overflow-safe
# $zstd_ratio integer/fractional scaling helper.
#
# The function is EXTRACTED VERBATIM by line range and compiled standalone,
# so a hand-copied duplicate of the arithmetic cannot quietly drift from
# production. No nginx tree and no libzstd needed: pure C, self-contained.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_filter_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-ratio-scaling-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT
mkdir -p "$OUT"

SIG="$(grep -n '^ngx_http_zstd_ratio_parts(uint64_t bytes_in' "$SRC" |
	head -1 | cut -d: -f1)"
if [ -z "$SIG" ]; then
	echo "FAIL: could not locate ngx_http_zstd_ratio_parts() in $SRC" >&2
	exit 1
fi

START=$((SIG - 1))
rel="$(tail -n "+${SIG}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
END=$((SIG + rel - 1))

{
	echo "/* Generated by test_ratio_scaling_unit.sh -- verbatim extraction"
	echo " * from $SRC:"
	echo " *   ngx_http_zstd_ratio_parts lines ${START}-${END}"
	echo " * Do not edit; re-run the script to regenerate. */"
	sed -n "${START},${END}p" "$SRC"
} >"$OUT/generated_ratio_parts.inc"

for marker in 'ngx_http_zstd_ratio_parts(uint64_t bytes_in' \
	'ratio_int' 'ratio_frac'; do
	if ! grep -q "$marker" "$OUT/generated_ratio_parts.inc"; then
		echo "FAIL: extracted fragment is missing \"$marker\"" >&2
		cat "$OUT/generated_ratio_parts.inc" >&2
		exit 1
	fi
done

cp ci/tools/test_ratio_scaling_unit.c "$OUT/test_ratio_scaling_unit.c"

"$CC" -Wall -Wextra -Werror -O2 -I"$OUT" \
	-o "$OUT/ratio_scaling_unit" "$OUT/test_ratio_scaling_unit.c"
"$OUT/ratio_scaling_unit"

echo "OK: ratio scaling unit fixture (extracted from current $SRC)"
