#!/bin/bash
# Unit fixture for the dictionary read loop, both layers.
#
# The loop, ngx_http_zstd_dict_file_read(), lives in
# src/ngx_http_zstd_dict_file.h, THE authoritative copy, and the fixture
# includes that header directly (the frame-probe and ratio fixtures'
# shape): no extracted or hand-copied duplicate to drift from production.
#
# The filter module's logging shell around it, ngx_http_zstd_read_dict_file(),
# is still `static` inside src/ngx_http_zstd_filter_module.c, so it is
# extracted verbatim by line range and compiled against the same scripted
# ngx_read_fd stub. An extraction that still contains a read call is
# refused: that is the loop restored inside the module, the copy drift the
# header exists to end. No nginx tree, no zstd needed -- pure C.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root: TWO levels.
cd "$(dirname "$0")/../.."

HDR="src/ngx_http_zstd_dict_file.h"
SRC="src/ngx_http_zstd_filter_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-read-dict-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

for marker in 'ngx_http_zstd_dict_file_read(ngx_fd_t fd, u_char \*buf, size_t size)' \
    'ngx_errno == NGX_EINTR' 'ngx_http_zstd_hex_nibble(u_char c)'; do
    if ! grep -q "$marker" "$HDR"; then
        echo "FAIL: $HDR lacks marker: $marker" >&2
        exit 1
    fi
done

if ! grep -Fq '#include "ngx_http_zstd_dict_file.h"' "$SRC"; then
    echo "FAIL: $SRC no longer includes $HDR" >&2
    exit 1
fi

# Locate the shell by its signature line (the `static ngx_int_t` return
# type sits on the line above it, as in this file's house style), so the
# extraction survives unrelated edits but fails loudly if the function is
# renamed or removed. Each locate pipeline ends in `|| true`: under
# pipefail a missing pattern would otherwise kill the script at the
# assignment, one line before the diagnostic that names what went missing.
SIG_LINE="$(grep -n '^ngx_http_zstd_read_dict_file(ngx_conf_t \*cf, ngx_fd_t fd, ngx_str_t \*path,$' "$SRC" | head -1 | cut -d: -f1 || true)"
if [ -z "$SIG_LINE" ]; then
    echo "FAIL: could not locate ngx_http_zstd_read_dict_file()'s definition in $SRC" >&2
    exit 1
fi

START_LINE=$((SIG_LINE - 1))
if ! sed -n "${START_LINE}p" "$SRC" | grep -q '^static ngx_int_t$'; then
    echo "FAIL: line $START_LINE in $SRC is not the expected 'static ngx_int_t' return-type line" >&2
    exit 1
fi

# First "^}" at column 0 after START_LINE closes the function.
REL_END="$(tail -n "+${START_LINE}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1 || true)"
if [ -z "$REL_END" ]; then
    echo "FAIL: could not find the closing brace of ngx_http_zstd_read_dict_file() in $SRC" >&2
    exit 1
fi
END_LINE=$((START_LINE + REL_END - 1))

{
    echo "/* Generated by test_read_dict_file_unit.sh -- verbatim extraction of"
    echo " * ngx_http_zstd_read_dict_file() from $SRC lines $START_LINE-$END_LINE."
    echo " * Do not edit; regenerate by running the script. */"
    sed -n "${START_LINE},${END_LINE}p" "$SRC"
} > "$OUT/generated_read_dict_file.inc"

# Routing: the shell must call the header's loop and must not read on its
# own. A mis-ranged extraction fails the first test; the loop restored
# inside the module fails the second.
if ! grep -q 'ngx_http_zstd_dict_file_read(fd, buf, size)' "$OUT/generated_read_dict_file.inc"; then
    echo "FAIL: extracted shell does not call ngx_http_zstd_dict_file_read() -- extraction range is wrong, or the module no longer routes through $HDR" >&2
    sed -n '1,30p' "$OUT/generated_read_dict_file.inc" >&2
    exit 1
fi
if grep -q 'ngx_read_fd(' "$OUT/generated_read_dict_file.inc"; then
    echo "FAIL: ngx_http_zstd_read_dict_file() reads on its own again; the loop belongs in $HDR" >&2
    exit 1
fi

$CC -std=gnu99 -Wall -Wextra -Werror -O1 \
    -I ci/tools -I "$OUT" \
    -o "$OUT/test_read_dict_file_unit" \
    ci/tools/test_read_dict_file_unit.c

"$OUT/test_read_dict_file_unit"

# The header itself must stay C89-clean for the portable build, on its own
# fallback (ngx_inline empty; no -D mask), against the real read(2). With
# the fallback empty every member is a plain static function, so the
# ones this program does not call are allowed to go unused.
printf '%s\n' \
    '#include <errno.h>' \
    '#include <fcntl.h>' \
    '#include <string.h>' \
    '#include <unistd.h>' \
    'typedef unsigned char u_char;' \
    'typedef int ngx_fd_t;' \
    'typedef struct { size_t len; u_char *data; } ngx_str_t;' \
    '#define ngx_read_fd(fd, buf, n) read(fd, buf, n)' \
    '#define ngx_errno errno' \
    '#define NGX_EINTR EINTR' \
    '#define NGX_INVALID_FILE -1' \
    '#define NGX_MAX_PATH 4096' \
    '#define ngx_memcpy memcpy' \
    '#define ngx_strcmp(a, b) strcmp((const char *) (a), (const char *) (b))' \
    '#define ngx_close_file close' \
    '#include "../../src/ngx_http_zstd_dict_file.h"' \
    'int main(void) {' \
    '    u_char b[8]; int fd = open("/dev/zero", O_RDONLY);' \
    '    if (fd < 0) return 2;' \
    '    if (ngx_http_zstd_dict_file_read(fd, b, sizeof(b)) != (ssize_t) sizeof(b)) return 1;' \
    '    return ngx_http_zstd_hex_nibble(0x41) == 10 && ngx_http_zstd_hex_nibble(0x47) == 0xff ? 0 : 1;' \
    '}' \
    >"$OUT/c89.c"
"$CC" -std=c89 -pedantic-errors -Wall -Wextra -Werror -Wno-unused-function \
    -O1 -I ci/tools -o "$OUT/dict_file_c89" "$OUT/c89.c"
"$OUT/dict_file_c89"

echo "OK: read_dict_file unit fixture (loop from $HDR, shell extracted from $SRC)"
