#!/bin/bash
# Unit fixture for the static module's probe-verdict cache.
#
# ngx_http_zstd_static_cached_verdict() and ngx_http_zstd_static_remember(),
# plus the table and the VERDICT_* constants they read, are all `static`
# inside ngx_http_zstd_static_module.c, so this extracts them verbatim by
# line range (the same technique as test_static_pread_unit.sh, whose shape
# this one follows) and compiles them standalone against the minimal type
# surface in test_static_verdict_cache_unit.c. No nginx tree, no zstd, no
# filesystem -- pure C.
#
# Extraction, not duplication: a hand-copied key comparison would drift from
# the shipped one and keep passing while production started ignoring a field.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root: TWO levels.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_static_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-verdict-cache-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

INC="$OUT/generated_verdict_cache.inc"

# --- slice 1: the VERDICT_* constants, the struct and the table ---------
#
# Anchored on the SLOTS #define and closed on the table's cursor
# declaration, so an edit that moves either end fails loudly here instead
# of silently extracting a partial or over-wide range.
DECL_START="$(grep -n '^#define NGX_HTTP_ZSTD_STATIC_BAD_CACHE_SLOTS ' "$SRC" \
    | head -1 | cut -d: -f1)"
DECL_END="$(grep -n '^static ngx_uint_t  ngx_http_zstd_static_bad_cache_next;$' "$SRC" \
    | head -1 | cut -d: -f1)"

if [ -z "$DECL_START" ] || [ -z "$DECL_END" ] || [ "$DECL_END" -le "$DECL_START" ]; then
    echo "FAIL: could not locate the verdict-cache declarations in $SRC" >&2
    exit 1
fi

# --- slice 2 and 3: the two helpers, each by its signature line ---------
extract_fn() {
    # $1 = exact signature line, $2 = expected return-type line above it
    local sig_re="$1" rettype="$2" sig start rel end

    sig="$(grep -n "$sig_re" "$SRC" | head -1 | cut -d: -f1)"
    if [ -z "$sig" ]; then
        echo "FAIL: could not locate a definition matching '$sig_re' in $SRC" >&2
        exit 1
    fi

    start=$((sig - 1))
    if ! sed -n "${start}p" "$SRC" | grep -q "^${rettype}\$"; then
        echo "FAIL: line $start in $SRC is not the expected '$rettype' line" >&2
        exit 1
    fi

    # First "^}" at column 0 after start closes the function.
    rel="$(tail -n "+${start}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
    end=$((start + rel - 1))

    sed -n "${start},${end}p" "$SRC"
}

{
    echo "/* Generated by test_static_verdict_cache_unit.sh -- verbatim"
    echo " * extraction from $SRC. Do not edit; regenerate by running the"
    echo " * script. */"
    sed -n "${DECL_START},${DECL_END}p" "$SRC" \
        | grep -v '^#if (NGX_HTTP_ZSTD_STATIC_HAVE_PROBE)$'
    echo
    extract_fn '^ngx_http_zstd_static_cached_verdict(ngx_str_t \*path, ngx_open_file_info_t \*of)$' \
        'static ngx_uint_t'
    echo
    extract_fn '^ngx_http_zstd_static_remember(ngx_str_t \*path, ngx_open_file_info_t \*of,$' \
        'static void'
} >"$INC"

# Non-vacuity. An empty or mis-ranged .inc would compile to nothing and
# "pass"; each grep below names one thing the fixture cannot test if it is
# missing from the slice.
for needle in \
    'NGX_HTTP_ZSTD_STATIC_VERDICT_GOOD' \
    'NGX_HTTP_ZSTD_STATIC_BAD_CACHE_SLOTS' \
    'entry->uniq == of->uniq' \
    'entry->valid = verdict' \
    'ngx_http_zstd_static_bad_cache_next = 0'; do
    if ! grep -q "$needle" "$INC"; then
        echo "FAIL: extracted .inc is missing '$needle' -- extraction range is wrong" >&2
        sed -n '1,20p' "$INC" >&2
        exit 1
    fi
done

$CC -std=gnu99 -Wall -Wextra -Werror -O1 \
    -I ci/tools -I "$OUT" \
    -o "$OUT/test_static_verdict_cache_unit" \
    ci/tools/test_static_verdict_cache_unit.c

"$OUT/test_static_verdict_cache_unit"
