#!/bin/bash
# Copyright (C) 2026 Thijs Eilander
# SPDX-License-Identifier: BSD-2-Clause
#
# Unit fixture for ngx_http_zstd_dcz_window_log() -- the dcz window log and
# its two operator clamps.
#
# This function is the single source of truth for a value computed in TWO
# places that must never disagree: ngx_http_zstd_acquire_cctx() packs it into
# the CCtx ring key, and ngx_http_zstd_filter_init_cctx() pushes it into
# libzstd. If they diverge, a request borrows a slot keyed on one window and
# compresses at another -- the contamination the ring key exists to prevent.
# A hand-copied duplicate of the arithmetic in a test would pass forever while
# production drifted, so the function and its ngx_http_zstd_ceil_log2()
# dependency are extracted VERBATIM by line range and compiled standalone.
#
# No nginx tree and no libzstd needed: pure C, self-contained.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_filter_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-dcz-wlog-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT
mkdir -p "$OUT"

extract() {   # $1 = start line, $2 = label; prints "start end"
    local start="$1" label="$2" rel end
    if [ -z "$start" ]; then
        echo "FAIL: could not locate $label in $SRC" >&2
        exit 1
    fi
    rel="$(tail -n "+${start}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
    end=$((start + rel - 1))
    echo "$start $end"
}

# --- ngx_http_zstd_ceil_log2() (dependency) ------------------------------
CEIL_SIG="$(grep -n '^ngx_http_zstd_ceil_log2(size_t x)' "$SRC" \
            | head -1 | cut -d: -f1)"
if [ -z "$CEIL_SIG" ]; then
    echo "FAIL: could not locate ngx_http_zstd_ceil_log2() in $SRC" >&2
    exit 1
fi
read -r CEIL_START CEIL_END < <(extract "$((CEIL_SIG - 1))" "ceil_log2")

# --- the window bound #defines -------------------------------------------
CAP_LINE="$(grep -n '^#define NGX_HTTP_ZSTD_DCZ_MAX_WINDOW_LOG' "$SRC" \
            | head -1 | cut -d: -f1)"
if [ -z "$CAP_LINE" ]; then
    echo "FAIL: could not locate NGX_HTTP_ZSTD_DCZ_MAX_WINDOW_LOG in $SRC" >&2
    exit 1
fi
MIN_LINE="$(grep -n '^#define NGX_HTTP_ZSTD_DCZ_MIN_WINDOW_LOG' "$SRC" \
            | head -1 | cut -d: -f1)"
if [ -z "$MIN_LINE" ]; then
    echo "FAIL: could not locate NGX_HTTP_ZSTD_DCZ_MIN_WINDOW_LOG in $SRC" >&2
    exit 1
fi

# --- ngx_http_zstd_dcz_window_log() (the function under test) ------------
DCZ_SIG="$(grep -n '^ngx_http_zstd_dcz_window_log(size_t dict_len' "$SRC" \
           | head -1 | cut -d: -f1)"
if [ -z "$DCZ_SIG" ]; then
    echo "FAIL: could not locate ngx_http_zstd_dcz_window_log() in $SRC" >&2
    exit 1
fi
read -r DCZ_START DCZ_END < <(extract "$((DCZ_SIG - 1))" "dcz_window_log")

{
    echo "/* Generated by test_dcz_window_log_unit.sh -- verbatim extraction"
    echo " * from $SRC:"
    echo " *   ceil_log2      lines ${CEIL_START}-${CEIL_END}"
    echo " *   window cap     line  ${CAP_LINE}"
    echo " *   dcz_window_log lines ${DCZ_START}-${DCZ_END}"
    echo " * Do not edit; re-run the script to regenerate. */"
    sed -n "${CAP_LINE}p" "$SRC"
    sed -n "${MIN_LINE}p" "$SRC"
    echo
    sed -n "${CEIL_START},${CEIL_END}p" "$SRC"
    echo
    sed -n "${DCZ_START},${DCZ_END}p" "$SRC"
} > "$OUT/generated_dcz_window_log.inc"

# Sanity: a source reflow must fail loudly here, not produce a garbage .inc
# that still compiles and "passes".
for marker in 'ngx_http_zstd_ceil_log2(size_t x)' \
              'NGX_HTTP_ZSTD_DCZ_MAX_WINDOW_LOG' \
              'NGX_HTTP_ZSTD_DCZ_MIN_WINDOW_LOG' \
              'ngx_http_zstd_dcz_window_log(size_t dict_len' \
              'budget_window_cap'; do
    if ! grep -q "$marker" "$OUT/generated_dcz_window_log.inc"; then
        echo "FAIL: extracted fragment is missing \"$marker\"" >&2
        cat "$OUT/generated_dcz_window_log.inc" >&2
        exit 1
    fi
done

cp ci/tools/test_dcz_window_log_unit.c "$OUT/test_dcz_window_log_unit.c"

"$CC" -Wall -Wextra -Werror -O2 -I"$OUT" \
    -o "$OUT/dcz_window_log_unit" "$OUT/test_dcz_window_log_unit.c"
"$OUT/dcz_window_log_unit"

echo "OK: dcz window-log unit fixture (extracted from current $SRC)"
