#!/bin/bash
# Unit fixture for ngx_http_zstd_static_probe_frame().
set -euo pipefail

cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_static_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-static-probe-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

SIG_LINE="$(grep -n '^ngx_http_zstd_static_probe_frame(const u_char \*hdr, size_t n, uint64_t \*window)$' "$SRC" | head -1 | cut -d: -f1)"
if [ -z "$SIG_LINE" ]; then
	echo "FAIL: could not locate ngx_http_zstd_static_probe_frame() in $SRC" >&2
	exit 1
fi

START_LINE=$((SIG_LINE - 1))
if ! sed -n "${START_LINE}p" "$SRC" | grep -q '^static ngx_int_t$'; then
	echo "FAIL: line $START_LINE in $SRC is not the expected return-type line" >&2
	exit 1
fi

REL_END="$(tail -n "+${START_LINE}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
END_LINE=$((START_LINE + REL_END - 1))

mkdir -p "$OUT"
{
	echo "/* Generated by test_static_probe_unit.sh -- verbatim extraction of"
	echo " * ngx_http_zstd_static_probe_frame() from $SRC lines $START_LINE-$END_LINE."
	echo " * Do not edit; regenerate by running the script. */"
	sed -n '270,275p' "$SRC"
	sed -n "${START_LINE},${END_LINE}p" "$SRC"
} >"$OUT/generated_static_probe.inc"

for marker in \
	'NGX_HTTP_ZSTD_STATIC_FRAME_RESERVED' \
	'fhd & 0x08' \
	'NGX_HTTP_ZSTD_STATIC_FRAME_WINDOW_BIG'; do
	if ! grep -q "$marker" "$OUT/generated_static_probe.inc"; then
		echo "FAIL: extracted probe fixture lacks marker: $marker" >&2
		exit 1
	fi
done

"$CC" -std=gnu99 -Wall -Wextra -Werror -O1 \
	-I ci/tools -I "$OUT" \
	-o "$OUT/test_static_probe_unit" \
	ci/tools/test_static_probe_unit.c

"$OUT/test_static_probe_unit"
