#!/bin/bash
# Unit fixture for ngx_http_zstd_release_cctx().
#
# THE DEFECT CLASS THIS GUARDS. Release resets the slot's context with
# ZSTD_CCtx_reset(ZSTD_reset_session_only). The unfixed code discards that
# call's return with (void), so a reset failure is invisible: slot->busy is
# still cleared to 0 and the slot goes straight back into the ring with a
# wedged context. acquire_cctx() then hands the SAME wedged slot to the next
# borrower (it does not distinguish "empty" from "reusable but broken" --
# only slot->cctx == NULL && !slot->busy means re-seedable), whose own full
# ZSTD_reset_session_and_parameters in ngx_http_zstd_filter_init_cctx() fails
# too, erroring that request. Nothing about this ever un-poisons the slot,
# so it fails every future borrower for the rest of the worker's life. This
# is an availability defect, not corruption: the acquire-path reset is
# checked and any request that gets a bad slot fails cleanly rather than
# emitting wrong bytes.
#
# The fix retires a slot whose release-time reset fails: free the context,
# set slot->cctx = NULL, and clear slot->busy -- the exact "empty AND not
# busy" pair acquire_cctx() already treats as re-seedable, per the profile
# walk in ngx_http_zstd_acquire_cctx() a few hundred lines up. This fixture
# proves that shape, not just "an error was logged".
#
# WHY A UNIT FIXTURE AND NOT THE HTTP FAULT-INJECTION PROBE. Forcing
# ZSTD_CCtx_reset() to fail at release time needs a scripted libzstd, and
# release_cctx() runs from a pool cleanup handler with only a slot pointer
# in hand -- there is no request-scoped fault-injection hook that reaches
# it. A direct unit fixture that fakes ZSTD_CCtx_reset() is the only way to
# force this exit.
#
# Extraction, not duplication: the function is `static` inside
# ngx_http_zstd_filter_module.c, so this extracts it verbatim by line range
# (the same technique as test_freecctxparams_unit.sh and
# test_read_dict_file_unit.sh) along with the ngx_http_zstd_cctx_slot_t /
# ngx_http_zstd_cctx_profile_t types it operates on, and compiles it
# standalone in test_release_cctx_unit.c against scripted ZSTD_* fakes. A
# hand-copied duplicate of the function would drift from the shipped code
# and keep passing while a real regression reintroduced the poisoned slot.
set -euo pipefail

# ci/tools/ -> ci/ -> repo root: TWO levels.
cd "$(dirname "$0")/../.."

SRC="src/ngx_http_zstd_filter_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/zstd-release-cctx-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT
mkdir -p "$OUT"

# --- the two slot/profile typedefs the function operates on --------------
# ngx_http_zstd_cctx_profile_t's opening brace is the "typedef struct {"
# line immediately followed by "uint64_t key;" -- anchor on that pair
# rather than on the enclosing #define/comment block, which is free to
# change independently of the type itself.
TYPE_START="$(grep -n -A1 '^typedef struct {$' "$SRC" \
              | grep -B1 'uint64_t key;' \
              | head -1 | cut -d: -f1 || true)"
if [ -z "$TYPE_START" ]; then
    echo "FAIL: could not locate ngx_http_zstd_cctx_profile_t start in $SRC" >&2
    exit 1
fi
TYPE_END="$(grep -n '^} ngx_http_zstd_cctx_slot_t;' "$SRC" | head -1 | cut -d: -f1 || true)"
if [ -z "$TYPE_END" ]; then
    echo "FAIL: could not locate ngx_http_zstd_cctx_slot_t end in $SRC" >&2
    exit 1
fi

# --- the function itself -------------------------------------------------
# Locate by its signature line (the "static void" return type sits on the
# line above it, as in this file's house style), so extraction survives
# unrelated edits but fails loudly if the function is renamed or removed.
SIG_LINE="$(grep -n '^ngx_http_zstd_release_cctx(void \*data)$' "$SRC" \
            | head -1 | cut -d: -f1 || true)"
if [ -z "$SIG_LINE" ]; then
    echo "FAIL: could not locate ngx_http_zstd_release_cctx()'s definition in $SRC" >&2
    exit 1
fi

FUNC_START=$((SIG_LINE - 1))
if ! sed -n "${FUNC_START}p" "$SRC" | grep -q '^static void$'; then
    echo "FAIL: line $FUNC_START in $SRC is not the expected 'static void' return-type line" >&2
    exit 1
fi

REL_END="$(tail -n "+${FUNC_START}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1 || true)"
if [ -z "$REL_END" ]; then
    echo "FAIL: could not find the closing '}' for ngx_http_zstd_release_cctx() in $SRC" >&2
    exit 1
fi
FUNC_END=$((FUNC_START + REL_END - 1))

{
    echo "/* Generated by test_release_cctx_unit.sh — verbatim extraction of"
    echo " * ngx_http_zstd_cctx_profile_t/ngx_http_zstd_cctx_slot_t from"
    echo " * $SRC lines $TYPE_START-$TYPE_END and"
    echo " * ngx_http_zstd_release_cctx() from lines $FUNC_START-$FUNC_END."
    echo " * Do not edit; regenerate by running the script. */"
    sed -n "${TYPE_START},${TYPE_END}p" "$SRC"
    echo
    sed -n "${FUNC_START},${FUNC_END}p" "$SRC"
} > "$OUT/generated_release_cctx.inc"

# Non-vacuity: the extraction must actually contain the ZSTD_freeCCtx(...)
# retirement call and the slot->cctx = NULL that makes a retired slot
# re-seedable. A mis-ranged .inc would compile to nothing (or a truncated
# function) and silently "pass" since the fake would never be exercised.
if ! grep -q 'ZSTD_freeCCtx(slot->cctx)' "$OUT/generated_release_cctx.inc"; then
    echo "FAIL: extracted .inc does not contain the slot retirement call -- extraction range is wrong or the fix regressed" >&2
    exit 1
fi

$CC -std=gnu99 -Wall -Wextra -Werror -O1 \
    -I ci/tools -I "$OUT" \
    -o "$OUT/test_release_cctx_unit" \
    ci/tools/test_release_cctx_unit.c

"$OUT/test_release_cctx_unit"
