/*
 * libFuzzer harness for ngx_http_zstd_accept_encoding().
 *
 * Why this target: it parses attacker-controlled Accept-Encoding header
 * bytes in C, does pointer arithmetic against ae->data / ae->len, and calls
 * the NUL-terminated ngx_strcasestrn() over the same buffer. That mismatch
 * (length-bounded vs. NUL-bounded) plus RFC 7231 q-value parsing is exactly
 * the bug class coverage-guided fuzzing finds and the Perl suite misses.
 *
 * The real function lives in ../ngx_http_zstd_common.h and depends on the
 * nginx tree. fuzz/extract_parser.sh slices just that function into
 * generated_parser.inc at build time, so we always fuzz the SHIPPED code
 * with no copy drift. ngx_shim.h provides the tiny nginx surface it needs
 * with faithful upstream semantics.
 *
 * Build (see fuzz/build.sh):
 *   clang -g -O1 -fsanitize=fuzzer,address,undefined \
 *       fuzz_accept_encoding.c -o fuzz_accept_encoding
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "ngx_shim.h"

/* Generated by fuzz/extract_parser.sh from ../ngx_http_zstd_common.h.
 * Contains the verbatim body of ngx_http_zstd_accept_encoding(). */
#include "generated_parser.inc"

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    /*
     * nginx header values are NUL-terminated in the request buffer.
     * Reproduce that invariant: copy the fuzz bytes into a heap buffer with
     * an explicit trailing NUL. ASAN will flag any read past `size` (the
     * len-bounded paths) AND any read past the NUL (the ngx_strcasestrn
     * path) because the allocation is sized exactly size + 1.
     */
    u_char *buf = (u_char *) malloc(size + 1);
    if (buf == NULL) {
        return 0;
    }

    if (size) {
        memcpy(buf, data, size);
    }
    buf[size] = '\0';

    ngx_str_t ae;
    ae.data = buf;
    ae.len  = size;

    ngx_int_t rc = ngx_http_zstd_accept_encoding(&ae);

    /* Result must be one of the two documented sentinels — anything else
     * means control flow fell through a path it should not have. */
    if (rc != NGX_OK && rc != NGX_DECLINED) {
        __builtin_trap();
    }

    free(buf);
    return 0;
}
