/*
 * libFuzzer harness for ngx_http_zstd_accept_encoding() and the
 * ngx_http_zstd_eval_qvalue() helper it calls.
 *
 * Why this target: it parses attacker-controlled Accept-Encoding header
 * bytes in C and does pointer arithmetic against ae->data / ae->len. The
 * parser is now a fully length-bounded token walker (no NUL reliance),
 * so this harness deliberately feeds it a buffer sized to EXACTLY
 * ae->len with NO trailing NUL — ASAN then flags any single byte read at
 * or past ae->len. Together with RFC 7231 q-value parsing that is
 * exactly the bug class coverage-guided fuzzing finds and the Perl suite
 * misses, and it is a hard regression gate against re-introducing a
 * NUL-bounded scan over the len-bounded buffer.
 *
 * The real functions live in ../ngx_http_zstd_common.h and depend on the
 * nginx tree. fuzz/extract_parser.sh slices just those functions into
 * generated_parser.inc at build time, so we always fuzz the SHIPPED code
 * with no copy drift. ngx_shim.h provides the tiny nginx surface it needs
 * with faithful upstream semantics.
 *
 * Build (see fuzz/build.sh):
 *   clang -g -O1 -fsanitize=fuzzer,address,undefined \
 *       fuzz_accept_encoding.c -o fuzz_accept_encoding
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "ngx_shim.h"

/* Generated by fuzz/extract_parser.sh from ../ngx_http_zstd_common.h.
 * Contains the verbatim bodies of ngx_http_zstd_eval_qvalue() and
 * ngx_http_zstd_accept_encoding(). */
#include "generated_parser.inc"

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    /*
     * The parser is fully length-bounded, so do NOT append a trailing
     * NUL: allocate exactly `size` bytes (one byte when size == 0, since
     * malloc(0) is implementation-defined). ASAN then turns any read at
     * or past ae->len — i.e. any reintroduced NUL-bounded scan — into an
     * immediate, reproducible heap-buffer-overflow failure.
     */
    size_t  alloc = size ? size : 1;
    u_char *buf = (u_char *) malloc(alloc);
    if (buf == NULL) {
        return 0;
    }

    if (size) {
        memcpy(buf, data, size);
    }

    ngx_str_t ae;
    ae.data = buf;
    ae.len  = size;

    ngx_int_t rc = ngx_http_zstd_accept_encoding(&ae);

    /* Result must be one of the two documented sentinels — anything else
     * means control flow fell through a path it should not have. */
    if (rc != NGX_OK && rc != NGX_DECLINED) {
        __builtin_trap();
    }

    free(buf);
    return 0;
}
