#!/usr/bin/env bash
# Unit fixture for ngx_http_compression_max_length_exceeded() (parent #227):
# the length-independent compression_max_length cap checked per iteration
# of the streaming body filter.
#
# The predicate is extracted VERBATIM by its signature from
# compression/ngx_http_compression_module.c and compiled standalone against
# test_max_length_cap_unit.c, natively and, when the toolchain can, with
# plain -m32 (no _FILE_OFFSET_BITS override): the one build shape with a
# 4-byte off_t, where the signed-cast form this predicate replaced
# truncated the uint64_t accumulator. A native or ILP32+LFS run alone would
# let a regression back to that form pass, so the -m32 pass is not optional
# coverage; it is skipped (exit 0) only where no 32-bit toolchain exists,
# unless REQUIRE_M32 is set to a truthy value (1/true/yes/on), in which
# case a missing toolchain fails loudly -- set in CI so a runner image that
# drops multilib loses this lens visibly.
set -euo pipefail
cd "$(dirname "$0")/../.."

SRC="compression/ngx_http_compression_module.c"
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/compression-max-length-cap.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

SIG='ngx_http_compression_max_length_exceeded(uint64_t bytes_in, ssize_t max_length)'
# Each locate pipeline ends in `|| true`: under pipefail a missing pattern
# would otherwise kill the script at the assignment, one line before the
# diagnostic that names what went missing.
SIG_LINE="$(grep -nF "$SIG" "$SRC" | head -1 | cut -d: -f1 || true)"
if [ -z "$SIG_LINE" ]; then
    echo "FAIL: could not locate ${SIG} in $SRC" >&2
    exit 1
fi
START_LINE=$((SIG_LINE - 1))
if ! sed -n "${START_LINE}p" "$SRC" | tr -d '\r' | grep -q '^static ngx_flag_t$'; then
    echo "FAIL: line $START_LINE of $SRC is not the predicate's 'static ngx_flag_t' return line" >&2
    exit 1
fi
REL_END="$(tail -n "+${START_LINE}" "$SRC" | tr -d '\r' | grep -n '^}' | head -1 | cut -d: -f1 || true)"
if [ -z "$REL_END" ]; then
    echo "FAIL: could not find the closing brace of ${SIG} in $SRC" >&2
    exit 1
fi
END_LINE=$((START_LINE + REL_END - 1))

{
    echo "/* Generated by test_max_length_cap_unit.sh: verbatim extraction of"
    echo " * $SRC lines ${START_LINE}-${END_LINE}. Do not edit. */"
    sed -n "${START_LINE},${END_LINE}p" "$SRC" | tr -d '\r'
} > "$OUT/generated_max_length_cap.inc"

for marker in "$SIG" 'NGX_CONF_UNSET' 'bytes_in > (uint64_t) max_length'; do
    if ! grep -qF "$marker" "$OUT/generated_max_length_cap.inc"; then
        echo "FAIL: extracted predicate lacks \"$marker\"" >&2
        cat "$OUT/generated_max_length_cap.inc" >&2
        exit 1
    fi
done

cp compression/tools/test_max_length_cap_unit.c "$OUT/"
"$CC" -std=c99 -Wall -Wextra -Werror -O2 -I "$OUT" \
    -o "$OUT/unit" "$OUT/test_max_length_cap_unit.c"
"$OUT/unit"
echo "OK: max_length cap unit fixture, native off_t"

require_m32="${REQUIRE_M32:-0}"
case "${require_m32,,}" in
    0 | "" | false | no | off) require_m32_set=0 ;;
    *) require_m32_set=1 ;;
esac

if "$CC" -m32 -x c -o /dev/null - <<<'int main(void){return 0;}' >/dev/null 2>&1; then
    "$CC" -m32 -std=c99 -Wall -Wextra -Werror -O2 -I "$OUT" \
        -o "$OUT/unit32" "$OUT/test_max_length_cap_unit.c"
    "$OUT/unit32"
    echo "OK: max_length cap unit fixture, 32-bit off_t (bytes_in > INT32_MAX)"
elif [ "$require_m32_set" = 1 ]; then
    echo "FAIL: no -m32 toolchain and REQUIRE_M32 is set; the 32-bit off_t pass cannot run" >&2
    exit 1
else
    echo "SKIP: no -m32 toolchain; the 32-bit off_t pass not run" >&2
fi
