#!/usr/bin/env bash
# Unit fixture for ngx_http_compression_read_dict_file().
#
# The helper is `static` inside ngx_http_compression_dict.c, so this
# extracts it VERBATIM by line range and compiles it standalone against a
# scripted ngx_read_fd stub in test_read_dict_file_unit.c. No nginx tree,
# no codec libs -- pure C. Extraction, not duplication: a hand-copied body
# would drift from the shipped code and keep passing while the real loop
# regressed. (Mirrors the standalone module's test_read_dict_file_unit.sh.)
set -euo pipefail

cd "$(dirname "$0")/.."          # compression/tools -> compression

CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/compression-read-dict-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

# Work on a CR-stripped copy: the source is checked out CRLF on Windows
# working trees, and the line-anchored grep/sed below must match on both
# CRLF and LF (CI is LF).
SRC="$OUT/dict_src.c"
tr -d '\r' < "ngx_http_compression_dict.c" > "$SRC"

# Locate the definition by its signature line (the `static ssize_t` return
# type sits on the line above it, this file's house style), so extraction
# survives unrelated edits but fails loudly if the function is renamed.
SIG_LINE="$(grep -n '^ngx_http_compression_read_dict_file(ngx_fd_t fd, u_char \*buf, size_t size)$' "$SRC" | head -1 | cut -d: -f1)"
if [ -z "$SIG_LINE" ]; then
    echo "FAIL: could not locate ngx_http_compression_read_dict_file()'s definition in $SRC" >&2
    exit 1
fi

START_LINE=$((SIG_LINE - 1))
if ! sed -n "${START_LINE}p" "$SRC" | grep -q '^static ssize_t$'; then
    echo "FAIL: line $START_LINE in $SRC is not the expected 'static ssize_t' return-type line" >&2
    exit 1
fi

# First "^}" at column 0 after START_LINE closes the function.
REL_END="$(tail -n "+${START_LINE}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
END_LINE=$((START_LINE + REL_END - 1))

{
    echo "/* Generated by test_read_dict_file_unit.sh -- verbatim extraction of"
    echo " * ngx_http_compression_read_dict_file() from $SRC lines $START_LINE-$END_LINE."
    echo " * Do not edit; regenerate by running the script. */"
    sed -n "${START_LINE},${END_LINE}p" "$SRC"
} > "$OUT/generated_read_dict_file.inc"

# Non-vacuity: the extraction must actually contain the loop. An empty or
# mis-ranged .inc would otherwise compile to nothing and "pass".
if [ "$(grep -c 'ngx_read_fd' "$OUT/generated_read_dict_file.inc")" -lt 1 ]; then
    echo "FAIL: extracted .inc contains no ngx_read_fd call -- extraction range is wrong" >&2
    sed -n '1,20p' "$OUT/generated_read_dict_file.inc" >&2
    exit 1
fi

"$CC" -std=gnu99 -Wall -Wextra -Werror -O1 \
    -I tools -I "$OUT" \
    -o "$OUT/test_read_dict_file_unit" \
    tools/test_read_dict_file_unit.c

"$OUT/test_read_dict_file_unit"
