#!/usr/bin/env bash
#
# Unit fixture for the body filter's caller-owned input cursor and lazy
# tail copy (the parent's test_input_chain_cursor_unit shape, re-derived
# for this module's three extracted helpers). The shipped functions are
# extracted verbatim, then compiled against a minimal nginx pool/chain
# shim -- ownership, retained-before-cursor ordering, and the
# allocation-failure boundary become deterministic without needing
# socket pressure to land at one exact event-loop iteration.
set -euo pipefail

cd "$(dirname "$0")/.."

SRC=ngx_http_compression_module.c
CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/compression-input-cursor-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

extract_function() {
    local signature="$1" label="$2" sig start rel end

    sig="$(grep -n "^${signature}" "$SRC" | head -1 | cut -d: -f1)"
    if [ -z "$sig" ]; then
        echo "FAIL: could not locate $label in $SRC" >&2
        exit 1
    fi

    start=$((sig - 1))
    rel="$(tail -n "+${start}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1)"
    end=$((start + rel - 1))
    sed -n "${start},${end}p" "$SRC"
}

{
    echo "/* Generated by test_input_chain_cursor_unit.sh from $SRC. */"
    extract_function 'ngx_http_compression_retain_input(' retain_input
    echo
    extract_function 'ngx_http_compression_next_in_buf(' next_in_buf
    echo
    extract_function 'ngx_http_compression_consume_in_link(' consume_in_link
} >"$OUT/generated_input_cursor.inc"

for marker in ngx_http_compression_retain_input \
              ngx_http_compression_next_in_buf \
              ngx_http_compression_consume_in_link \
              'ngx_free_chain(r->pool, cl)' \
              'ctx->last_in = &ctx->in'; do
    if ! grep -q "$marker" "$OUT/generated_input_cursor.inc"; then
        echo "FAIL: extracted fragment is missing $marker" >&2
        exit 1
    fi
done

# The body-filter return boundary is part of the contract but
# deliberately not duplicated in the C shim. Pin the production wiring:
# the unconsumed cursor must be retained at the ship: choke point with
# its failure on the terminal path, and the consumer loop must actually
# route through the extracted pair.
if ! sed -n '/^ship:/,/if (out == NULL)/p' "$SRC" \
    | grep -A3 'ngx_http_compression_retain_input' \
    | grep -q 'return NGX_ERROR;'
then
    echo "FAIL: ship: no longer retains the cursor tail terminally on failure" >&2
    exit 1
fi

if ! grep -q 'ngx_http_compression_next_in_buf(ctx, in, &retained)' "$SRC" \
   || ! grep -q 'ngx_http_compression_consume_in_link(r, ctx, &in, retained)' \
        "$SRC"
then
    echo "FAIL: the body-filter loop no longer routes through the extracted pair" >&2
    exit 1
fi

cp tools/test_input_chain_cursor_unit.c "$OUT/"
"$CC" -std=c99 -O2 -Wall -Wextra -Werror -I"$OUT" \
    -o "$OUT/test_input_chain_cursor_unit" \
    "$OUT/test_input_chain_cursor_unit.c"
timeout 30s "$OUT/test_input_chain_cursor_unit"
