#!/usr/bin/env bash
# Unit fixture for ngx_http_brotli_read_dict_file().
#
# The helper is `static` inside filter/ngx_http_brotli_filter_module.c, so
# this extracts it VERBATIM by line range and compiles it standalone
# against a scripted ngx_read_fd stub in test_read_dict_file_unit.c. No
# nginx tree, no libbrotli -- pure C. Extraction, not duplication: a
# hand-copied body would drift from the shipped code and keep passing while
# the real loop regressed. (Mirrors nginx-zstd-module's #195 fixture.)
set -euo pipefail

cd "$(dirname "$0")/.."          # tools -> repo root

CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/brotli-read-dict-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

# Work on a CR-stripped copy: the source is checked out CRLF on Windows
# working trees, and the line-anchored grep/sed below must match on both
# CRLF and LF (CI is LF).
SRC="$OUT/brotli_src.c"
tr -d '\r' < "filter/ngx_http_brotli_filter_module.c" > "$SRC"

# Google K&R house style here: the return type and name share the
# signature line, and the forward DECLARATION opens identically -- both
# read "static ssize_t <name>(ngx_fd_t fd, u_char* buf,". They diverge only
# on the next line: the definition ends "size_t size) {", the declaration
# "size_t size);". Pick the one whose continuation opens a body.
START_LINE="$(awk '
    /^static ssize_t ngx_http_brotli_read_dict_file\(ngx_fd_t fd, u_char\* buf,$/ {
        cand = NR; next
    }
    cand && NR == cand + 1 {
        if ($0 ~ /size_t size\) \{$/) { print cand; exit }
        cand = 0
    }
' "$SRC")"
if [ -z "$START_LINE" ]; then
    echo "FAIL: could not locate ngx_http_brotli_read_dict_file()'s definition" >&2
    exit 1
fi

# First "^}" at column 0 after START_LINE closes the function. `|| true`
# so a miss reaches the diagnostic instead of ending the script at the
# assignment under pipefail.
REL_END="$(tail -n "+${START_LINE}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1 || true)"
if [ -z "$REL_END" ]; then
    echo "FAIL: could not find the closing brace of ngx_http_brotli_read_dict_file()" >&2
    exit 1
fi
END_LINE=$((START_LINE + REL_END - 1))

{
    echo "/* Generated by test_read_dict_file_unit.sh -- verbatim extraction of"
    echo " * ngx_http_brotli_read_dict_file() lines $START_LINE-$END_LINE."
    echo " * Do not edit; regenerate by running the script. */"
    sed -n "${START_LINE},${END_LINE}p" "$SRC"
} > "$OUT/generated_read_dict_file.inc"

# Non-vacuity: the extraction must actually contain the loop.
if [ "$(grep -c 'ngx_read_fd' "$OUT/generated_read_dict_file.inc")" -lt 1 ]; then
    echo "FAIL: extracted .inc contains no ngx_read_fd call -- extraction range is wrong" >&2
    sed -n '1,20p' "$OUT/generated_read_dict_file.inc" >&2
    exit 1
fi

"$CC" -std=gnu99 -Wall -Wextra -Werror -O1 \
    -I tools -I "$OUT" \
    -o "$OUT/test_read_dict_file_unit" \
    tools/test_read_dict_file_unit.c

"$OUT/test_read_dict_file_unit"
