#!/usr/bin/env bash
# Unit fixture for ngx_http_brotli_ratio_parts() -- the overflow-safe
# $brotli_ratio split (the zstd siblings' #294 shape).
#
# The helper is `static` inside filter/ngx_http_brotli_filter_module.c, so
# this extracts it VERBATIM by line range and compiles it standalone against
# an unsigned __int128 oracle in test_ratio_scaling_unit.c. No nginx tree,
# no libbrotli -- pure C. Extraction, not duplication: a hand-copied body
# would drift from the shipped code and keep passing while the real
# arithmetic regressed.
set -euo pipefail

cd "$(dirname "$0")/.."          # tools -> repo root

CC="${CC:-cc}"
OUT="$(mktemp -d "${TMPDIR:-/tmp}/brotli-ratio-unit.XXXXXX")"
trap 'rm -rf "$OUT"' EXIT

# CR-stripped copy: Windows working trees are checked out CRLF and the
# line-anchored grep below must match on both (CI is LF).
SRC="$OUT/brotli_src.c"
tr -d '\r' < "filter/ngx_http_brotli_filter_module.c" > "$SRC"

# Each locate pipeline ends in `|| true`: under pipefail a missing pattern
# would otherwise kill the script at the assignment, one line before the
# diagnostic that names what went missing.
START_LINE="$(grep -n '^static void ngx_http_brotli_ratio_parts(uint64_t bytes_in, uint64_t bytes_out,$' \
              "$SRC" | head -1 | cut -d: -f1 || true)"
if [ -z "$START_LINE" ]; then
    echo "FAIL: could not locate ngx_http_brotli_ratio_parts() in the filter" >&2
    exit 1
fi
REL_END="$(tail -n "+${START_LINE}" "$SRC" | grep -n '^}' | head -1 | cut -d: -f1 || true)"
if [ -z "$REL_END" ]; then
    echo "FAIL: could not find the closing brace of ngx_http_brotli_ratio_parts()" >&2
    exit 1
fi
END_LINE=$((START_LINE + REL_END - 1))

{
    echo "/* Generated by test_ratio_scaling_unit.sh -- verbatim extraction"
    echo " * from filter/ngx_http_brotli_filter_module.c lines ${START_LINE}-${END_LINE}."
    echo " * Do not edit. */"
    sed -n "${START_LINE},${END_LINE}p" "$SRC"
} > "$OUT/generated_ratio_parts.inc"

# The variable must actually route through the helper: a reintroduced
# inline `* 100 /` or `* 1000 /` would leave this fixture green while
# $brotli_ratio overflowed again.
if grep -Eq 'bytes_in \* (100|1000) / ctx->bytes_out' "$SRC"; then
    echo "FAIL: \$brotli_ratio no longer routes through ratio_parts()" >&2
    exit 1
fi
if ! grep -q 'ngx_http_brotli_ratio_parts(ctx->bytes_in, ctx->bytes_out' "$SRC"; then
    echo "FAIL: \$brotli_ratio no longer calls ratio_parts()" >&2
    exit 1
fi

cp tools/test_ratio_scaling_unit.c "$OUT/"
"$CC" -std=gnu99 -O2 -Wall -Wextra -Werror -I"$OUT" \
    -o "$OUT/test_ratio_scaling_unit" "$OUT/test_ratio_scaling_unit.c"
timeout 60s "$OUT/test_ratio_scaling_unit"
